# Generated by Django 4.2.7 on 2024-03-22 00:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("book_listings", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="meetuprequest",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="connectionfeepaid",
            name="book_listing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="book_listings.booklisting",
            ),
        ),
        migrations.AddField(
            model_name="connectionfeepaid",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="completedlisting",
            name="listing",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="book_listings.booklisting",
            ),
        ),
        migrations.AddField(
            model_name="booklisting",
            name="buyer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="purchased_listings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="booklisting",
            name="owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_listings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
