# Generated by Django 4.2.7 on 2024-03-22 01:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book_listings", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="meetuprequest",
            name="location_latitude",
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name="meetuprequest",
            name="location_longitude",
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name="meetuprequest",
            name="meetup_time",
            field=models.DateTimeField(null=True),
        ),
    ]
