# Generated by Django 4.2.7 on 2024-04-15 18:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_listings', '0003_meetuprequest_location_latitude_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='completedlisting',
            old_name='rating',
            new_name='seller_rating',
        ),
        migrations.AddField(
            model_name='completedlisting',
            name='buyer_rating',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
