# Generated by Django 4.2.7 on 2024-03-22 00:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="stripe_id",
            field=models.CharField(default=None, max_length=32, null=True, unique=True),
        ),
    ]
